### ISSUE TITLE
Unable to edit the slots in the Appointment Booking which are already created.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#14]
Unable to edit the slots in the Appointment Booking which are already created.

**Video**

https://github.com/bagisto/booking-product/assets/92721837/c84f9e4b-b44e-4a1a-a930-f10c8eb6687e

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, 
Now in the master, we have updated the design, and now the edit feature is no longer used in Appointment Booking.

[Please check Here ](https://prnt.sc/QPIZqJta12JB)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the create, delete and edit slot has been modified. Please check the screenshot below.

**Screenshot**

![Delete Field](https://github.com/bagisto/booking-product/assets/92721837/3ecac3ba-8481-4200-a21b-4fc40928e6d5)
