### ISSUE TITLE
We should not be able to store same time frame in the appointment booking.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#16]
When we check the details related to the appointment booking product, there we should not be able to save the same time in slots.
This is appearing in both cases **Same Slot For All days** either Yes or No.

Please check the screenshots for the issues.

Screenshot 1 - https://prnt.sc/brkZhNCpbUE9

Screenshot 2 - https://prnt.sc/v0NDJI-EvThd

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, 

This issue is fixed in master. Now the dublicate entry is skipped. only accepted 1 entry for 1 time frame.

**Comment by ashishkumar-webkul** [comment]
@amit-webkul 

Check  the screenshot [here](https://prnt.sc/FguSPbOjevgb), we are still able to see duplicate entry.

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, 

Kindly save the product after editing. Now you are unable to face this type of error.

**Comment by ashishkumar-webkul** [comment]
Checked and found that the appointment booking product same day multiple slots are added. please check the video for reference.

**Video**


https://github.com/bagisto/booking-product/assets/92721837/88603ba5-4f93-431d-8768-0375fcce118b
