### ISSUE TITLE
When creating Booking Product -> Translation missing.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#3]
**Description**

When we create a booking product there we can see that the  translation is missing.

**Steps to Reproduce**

1. Go to Admin -> Catalog -> Products -> Create Product.
2. Check the drop-down for product type.
3.  See the translation is missing.

**Actual Concern**

Currrently we can see that the Translation  is missing.

**Screenshot**

Please find  the screenshot [here](https://prnt.sc/NLKQh2Pqfb47)

**Expected Result**

Correct Translation -> **Booking Product**

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, 

This issue is appearing from the core. We have fixed the issue inside the core. Kindly update the core bagisto with new updates. After that, the issue does not appear.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the issue related to the translation is working fine with the latest version of Bagisto. Kindly check the screenshot [here](https://prnt.sc/PAQzC15nPrj1).

hence I am closing the issue.
