### ISSUE TITLE
Time Duration and Location, UI issue in default booking Product View Page.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#37]
Time Duration and Location, UI issue in default booking Product View Page.
Booking Type -> Default Booking -> Many Bookings for One.

Please find the screenshot below.

![Image 1](https://github.com/bagisto/booking-product/assets/92721837/509f6adb-760e-4289-9feb-9b7d85449661)

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir,
This is not an issue, just because this design was provided by our design team. Please look at the [design](https://prnt.sc/yagmq2ne9GnQ) provided by the design team.

**Comment by ashishkumar-webkul** [comment]
As per the discusioon that this is an invalid issue because this is set as per design. Hence I am marking this issue as Invalid and closing the same.
