### ISSUE TITLE
Unable to See the booking information in Admin End Grid View.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#43]
### Issue Description

After complete checkout and  completing the order process from admin, when we check  the Admin Booking Product details, there Unable to See the booking information in Admin End Grid View. 

### Preconditions

1. User must be logged in.
2. User must have purchased booking products.

### Steps to reproduce

1. Go to Admin -> Sales -> Orders -> Complete the order.
2. Go to Admin -> Sales -> Booking Products -> Click on Grid View
3. There we are unable to see any information.

### Expected Result

We should be able to see the details related to booking there.

### Actual Result

Please check the video for reference.

**Video**

https://github.com/bagisto/booking-product/assets/92721837/e0656956-ed21-452b-89d4-114bea3d41a2

**Comment by amit-webkul** [comment]
@ashishkumar-webkul ,

Please take a new pull from github just because I have checked with the new setup of the booking product and found there is no issue regarding the screenshot and description.

Everything is working fine. Take a look [here](https://prnt.sc/wkzN9nc8oK12)

**Comment by ashishkumar-webkul** [comment]
@amit-webkul 

I have installed  the boooking product module with fresh installation of Bagisto V2.1.1 and then checking the same. Please find the screenshot below.

**Screenshot**

![Screenshot from 2024-03-05 19-34-38](https://github.com/bagisto/booking-product/assets/92721837/5eec7e63-c1dd-4744-a72c-303197296d51)

**Comment by ashishkumar-webkul** [comment]
Checked and found that the details are appearing in the Grid view. Hence I am closing the issue, please find the screenshot.

**Screenshot**

![Screenshot from 2024-03-28 15-39-22](https://github.com/bagisto/booking-product/assets/92721837/7d31ef69-d629-40f7-ac6b-24b664348171)
