### ISSUE TITLE
Event Booking -> Tickets Valid from and to Dates are not working. Unable to enter the dates.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#46]
### Issue Description
When creating a new Event Booking Product, there when we add Event Tickets, there we have options to add Ticktes details and price. In tickets we have options to set dates for Ticket. They are not working.

### Preconditions

1. Admin Should be logged in.
2. Booking Product module must be added.

### Steps to reproduce

1. Go to Admin -> Catalog -> Products -> Create Booking Product.
2. Select Booking Type -> Event
3. Fill the form -> Now fill Tickets details.
4. Now Select the dates and then we can see that  we are unable to select the dates.
5. Cheked and found that dates are selected when we are filling Special price.
 
### Expected Result

We should be able to select the dates without the special price entry as well.

**Video**

https://github.com/bagisto/booking-product/assets/92721837/4dc4f16a-dcc6-4cf4-b8f1-f471349be43d

### Actual Result

Currently we can see tht we are unable to add dates.

**Video**

https://github.com/bagisto/booking-product/assets/92721837/43948582-1ee1-43b2-8d90-c7fbb7534175

**Comment by suraj-webkul** [comment]
@ashishkumar-webkul sir 

As I tested, this issue is not replicating on my side, sir.

**Comment by ashishkumar-webkul** [comment]
Checked and Found that now we are able to edit the special price in event booking products. Please check the video for reference.

**Video**

https://github.com/bagisto/booking-product/assets/92721837/e083e1df-5a58-49ad-b8d7-cfa98b3c8c6a
