### ISSUE TITLE
Event Booking -> We should not be selecting dates of tickets outside the Event Date.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#49]
### Issue Description
When we are creating a Event Boooking Product and there we have selected the dates of booking and when we  add Tickets and there we are selecting the tickets dates after the Event is expired. We are able to save the date and also save the product.

### Preconditions

1. Admin must be logged in.

### Steps to reproduce

1. Go to Admin End -> Catalog -> Products -> Create a Event Booking Product.
2. After Event Date selection -> Add Ticket -> Now select the date outside the Event.
3. Save the product.

### Expected Result

We should not be able to select the  dates of tickets after the event are closed.

### Actual Result
Event Booking Tickets dates are selected after the event is getting expired. 

**Video**

https://github.com/bagisto/booking-product/assets/92721837/cb194d5a-df83-4c1a-9e5b-967086cc813e

**Comment by ashishkumar-webkul** [comment]
Checked and found that the issue is not fixed. We are still able to save the tickets after the event is expired.

**Video**


https://github.com/bagisto/booking-product/assets/92721837/2cf1f63b-b1ff-48b2-b3a3-03de6c786c2a

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir , 
The outside date of the tickets is related to the ticket, and the inside date of the ticket is related to the ticket special price.
Both are different.

**Comment by ashishkumar-webkul** [comment]
As per the discussion with Amit it was found that the time frame selected in ticket is of the Special Price, Hence this issue is not valid. And Marking this issue as closed.
