### ISSUE TITLE
Getting Console Errors in Default Booking product  -> One Booking for Many Days Product View Page. 

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#58]
### Issue Description

After creating the Booking Product Default Booking Type, One Booking for Many Days Product View Page in Shop front. there we can see that the console errors are appearing.

### Preconditions

1. Booking Product module must be installed.
2. Admin Should be logged in.

### Steps to reproduce

1. Go to Admin -> Catalog -> Products -> Create Booking product.
2. Select Booking Type -> Default Booking.
3. Now select booking information -> One Booking for Many Days.
4. Fill the details. -> Save -> Check the product view page -> There we can see that the console errors are appearing.

### Expected Result

There should be no errors in the console.

### Actual Result
Currently we can see  that the issue is appearing in console.  Please check the screenshot for reference.

**Screenshot**

![Screenshot from 2024-03-27 11-03-01](https://github.com/bagisto/booking-product/assets/92721837/1458f166-cc9c-4b84-aea3-9483c7dacb0a)

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, 

The issue has not been reproduced.

**Comment by ashishkumar-webkul** [comment]
AS per checking the concern it was found that the errors are appearing due to debugger and chrome broweser issue, hence I am closing this issue.
