### ISSUE TITLE
Add Translation for Select Slot in all locale.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#78]
Add Translation for Select Slot in all locale.

Please find the screenshot ->  https://scrsht.com/0ddb1127

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, Here, the translation is already added. I have checked and found.

![Screenshot from 2024-04-08 13-06-33](https://github.com/bagisto/booking-product/assets/121479029/96a71df3-0143-4a36-9fe3-ec9a506a3905)

**Comment by ashishkumar-webkul** [comment]
Checked and found that the translation is appearing now. Hence I am closing the issue please find the screenshots below.

![Screenshot from 2024-04-08 13-34-39](https://github.com/bagisto/booking-product/assets/92721837/215b5aac-2ef7-4a52-abb5-c4068fcbac1b)
![Screenshot from 2024-04-08 13-36-47](https://github.com/bagisto/booking-product/assets/92721837/b3afc546-f8b8-468c-9f0e-1f86d6744f72)
![Screenshot from 2024-04-08 13-36-57](https://github.com/bagisto/booking-product/assets/92721837/6b9d383f-bda6-43b1-a04f-7c6e15abba68)
