### ISSUE TITLE
RTL view -> Please check the UI issue in the booking product slots time format.

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#79]
Please check the UI issue in the booking product slots time format.

Issue image below.

![Screenshot from 2024-04-08 12-11-59](https://github.com/bagisto/booking-product/assets/92721837/d4be8685-f51f-46d3-860e-5434d16f9c32)

Here we can see that, In arabic translation or RTL view, there the hyphen symbol must be in middle.

**Correct Format in RTL -> AM 05:00 - AM 06:00**

**Issue Format in RTL -> AM - 05:00 AM 06:00**

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, Their is no issue with UI. I also checked for the same issue in the previous version. The slots are coming in the previous version and are the same as now. 

![Screenshot from 2024-04-08, 13-32-14](https://github.com/bagisto/booking-product/assets/121479029/1210b845-8cc3-4221-8ee3-1e7769824ead)

**Comment by ashishkumar-webkul** [comment]
As per checking the same in Old version with @amit-webkul, it seems like that issue is being coming since previous version hence I am adding this issue in discussion.
