### ISSUE TITLE
Undefined array key "icon"

### ISSUE THREAD

**Issue by max3455** [bagisto/booking-product#84]
**Issue Description**
After the fresh installation Bagisto 2.1.2 and Booking-product getting error Undefined array key "icon".

**Preconditions**
Clean installation Bagisto 2.1.2 on local WAMP server using Composer (https://webkul.com/blog/laravel-ecommerce-website/)
Afterwards, install Booking-product using the Readme guide.

**Steps to reproduce**
During installation Booking-product, at the third installation point, after adding the line Webkul\BookingProduct\Providers\BookingProductServiceProvider::class, in the app.php, I reload the admin page and get an error.

https://github.com/bagisto/booking-product/assets/16278449/09b8af58-7ce2-4ab5-84c6-618713ba4315

**Comment by elmehdimrh** [comment]
in file : packages/Webkul/BookingProduct/src/Config/menu.php
change _icon-class_ to **icon**
[
        'key'        => 'sales.bookings',
        'name'       => 'booking::app.admin.sales.bookings.title',
        'route'      => 'admin.sales.bookings.index',
        'sort'       => 6,
        'icon-class' => '',
    ],
