### ISSUE TITLE
Unable to Delete the Default Booking Product - Many For One Booking slots

### ISSUE THREAD

**Issue by ashishkumar-webkul** [bagisto/booking-product#9]
Unable to Delete the Default Booking Product - Many For One Booking slots

**Video**

https://github.com/bagisto/booking-product/assets/92721837/d1555647-0aaf-4681-b2de-819b5da9f2b0

**Expected Result**

Either we should not show delete or if delete is shared then we should be able to delete the same.

**Comment by amit-webkul** [comment]
@ashishkumar-webkul sir, 
This issue is fixed in the master.

![Screenshot from 2024-01-24 16-34-49](https://github.com/bagisto/booking-product/assets/121479029/8635be33-15ed-4298-863d-6751ccdffc59)

**Comment by ashishkumar-webkul** [comment]
Checked and Found that the delete button functionality has been modified to cross button at the slots. Please check the screenshot and hence I am closing the issue.

**Screenshot**

![Delete Field](https://github.com/bagisto/booking-product/assets/92721837/e641dad4-9e51-4643-9c38-c2126901342e)
